steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update development server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh instance-1 --zone=us-west1-b --command='echo hello world from code build'