steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update development server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh --zone=us-west1-b --project=brown-hope instance-1