steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update development server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh --zone=us-west1-b --project=brown-hope instance-1 --command='cd /home/mack_foggia/OldCapstoneProject && \
                                                                                    sudo docker-compose down && \
                                                                                    git pull origin development && \
                                                                                    sh -c 'sudo docker-compose up --build''