name: CI for the old project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - run: pushd 
      - run: cd ./front
      - run: npm test
    
