# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    # Test
    - uses: actions/checkout@v2
    - name: Run Frontend Tests
      run: |
          cd ./front
          npm install
          npm test
          
    - name: Run Backend Tests
      run: |
          cd ./back
          npm install
          npm test

